package com.phanduy.utils;

/**
 * Created by duyuno on 7/6/16.
 */
public class CountryCode {

    public static final String COUNTRY_NAME[] = new String[] {
            "Afghanistan",
            "Åland Islands",
            "Albania",
            "Algérie",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Ascension",
            "Úc",
            "Australian External Territories",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Barbuda",
            "Belarus",
            "Bỉ",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bonaire",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brasil",
            "British Indian Ocean Territory",
            "British Virgin Islands",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burma",
            "Burundi",
            "Campuchia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Caribbean Netherlands",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chatham Island, New Zealand",
            "Chile",
            "Trung Quốc",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, Democratic Republic of the (Zaire)",
            "Cook Islands",
            "Costa Rica",
            "Bờ Biển Ngà",
            "Croatia",
            "Cuba",
            "Guantanamo Bay, Cuba",
            "Curaçao",
            "Síp",
            "Cộng hòa Séc",
            "Đan Mạch",
            "Diego Garcia",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Easter Island",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Ellipso (Mobile Satellite service)",
            "EMSAT (Mobile Satellite service)",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands",
            "Đảo Faroe",
            "Fiji",
            "Phần Lan",
            "Pháp",
            "French Antilles",
            "French Guiana",
            "French Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Đức",
            "Ghana",
            "Gibraltar",
            "Global Mobile Satellite System (GMSS)",
            "Globalstar (Mobile Satellite Service)",
            "Hy Lạp",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hồng Kông",
            "Hungary",
            "Iceland",
            "ICO Global (Mobile Satellite Service)",
            "Ấn Độ",
            "Indonesia",
            "Inmarsat SNAC",
            "International Freephone Service",
            "International Shared Cost Service (ISCS)",
            "Iran",
            "Iraq",
            "Ireland",
            "Iridium (Mobile Satellite service)",
            "Isle of Man",
            "Israel",
            "Ý",
            "Jamaica",
            "Jan Mayen",
            "Nhật Bản",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Triều Tiên",
            "Hàn Quốc",
            "Kuwait",
            "Kyrgyzstan",
            "Lào",
            "Latvia",
            "Liban",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Litva",
            "Luxembourg",
            "Ma Cao",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Đảo Marshall",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "México",
            "Micronesia, Federated States of",
            "Đảo Midway, Mỹ",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Maroc",
            "Mozambique",
            "Namibia",
            "Nauru",
            "Nepal",
            "Hà Lan",
            "Nevis",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Đảo Norfolk",
            "Đảo Northern Mariana",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestinian territories",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Đảo Pitcairn",
            "Ba Lan",
            "Bồ Đào Nha",
            "Puerto Rico",
            "Qatar",
            "Réunion",
            "România",
            "Nga",
            "Rwanda",
            "Saba",
            "Saint Barthélemy",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin (France)",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "São Tomé and Príncipe",
            "Ả Rập Saudi",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Sint Eustatius",
            "Sint Maarten (Netherlands)",
            "Slovakia",
            "Slovenia",
            "Đảo Solomon",
            "Somalia",
            "Nam Phi",
            "Đảo South Georgia và South Sandwich",
            "South Ossetia",
            "South Sudan",
            "Tây Ban Nha",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard",
            "Swaziland",
            "Thụy Điển",
            "Thụy Sĩ",
            "Syria",
            "Đài Loan",
            "Tajikistan",
            "Tanzania",
            "Thái Lan",
            "Thuraya (Mobile Satellite service)",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tristan da Cunha",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "Các Tiểu vương quốc Ả Rập Thống nhất",
            "Vương Quốc Anh",
            "Mỹ",
            "Universal Personal Telecommunications (UPT)",
            "Uruguay",
            "Đảo US Virgin",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vatican City State (Holy See)",
            "Việt Nam",
            "Wake Island, USA",
            "Wallis and Futuna",
            "Yemen",
            "Zambia",
            "Zanzibar",
            "Zimbabwe"
    };

    public static final int COUNTRY_CODE[] = new int[] {
            93,
            358,
            355,
            213,
            1684,
            376,
            244,
            1264,
            1268,
            54,
            374,
            297,
            247,
            61,
            672,
            43,
            994,
            1242,
            973,
            880,
            1246,
            1268,
            375,
            32,
            501,
            229,
            1441,
            975,
            591,
            5997,
            387,
            267,
            55,
            246,
            1284,
            673,
            359,
            226,
            95,
            257,
            855,
            237,
            1,
            238,
            5997,
            1345,
            236,
            235,
            64,
            56,
            86,
            61,
            61,
            57,
            269,
            242,
            243,
            682,
            506,
            225,
            385,
            53,
            5399,
            5999,
            357,
            420,
            45,
            246,
            253,
            1767,
            1849,
            670,
            56,
            593,
            20,
            503,
            8813,
            88213,
            240,
            291,
            372,
            251,
            500,
            298,
            679,
            358,
            33,
            596,
            594,
            689,
            241,
            220,
            995,
            49,
            233,
            350,
            881,
            8819,
            30,
            299,
            1473,
            590,
            1671,
            502,
            44,
            224,
            245,
            592,
            509,
            504,
            852,
            36,
            354,
            8811,
            91,
            62,
            870,
            800,
            808,
            98,
            964,
            353,
            8817,
            44,
            972,
            39,
            1876,
            4779,
            81,
            44,
            962,
            77,
            254,
            686,
            850,
            82,
            965,
            996,
            856,
            371,
            961,
            266,
            231,
            218,
            423,
            370,
            352,
            853,
            389,
            261,
            265,
            60,
            960,
            223,
            356,
            692,
            596,
            222,
            230,
            262,
            52,
            691,
            1808,
            373,
            377,
            976,
            382,
            1664,
            212,
            258,
            264,
            674,
            977,
            31,
            1869,
            687,
            64,
            505,
            227,
            234,
            683,
            672,
            1670,
            47,
            968,
            92,
            680,
            970,
            507,
            675,
            595,
            51,
            63,
            64,
            48,
            351,
            1939,
            974,
            262,
            40,
            7,
            250,
            5994,
            590,
            290,
            1869,
            1758,
            590,
            508,
            1784,
            685,
            378,
            239,
            966,
            221,
            381,
            248,
            232,
            65,
            5993,
            1721,
            421,
            386,
            677,
            252,
            27,
            500,
            99534,
            211,
            34,
            94,
            249,
            597,
            4779,
            268,
            46,
            41,
            963,
            886,
            992,
            255,
            66,
            88216,
            228,
            690,
            676,
            1868,
            2908,
            216,
            90,
            993,
            1649,
            688,
            256,
            380,
            971,
            44,
            1,
            878,
            598,
            1340,
            998,
            678,
            58,
            39066,
            84,
            1808,
            681,
            967,
            260,
            255,
            263
    };

    public static int getCodePosition(int code) {
        for(int i = 0, length = COUNTRY_CODE.length; i < length; i++) {
            if(COUNTRY_CODE[i] == code) {
                return i;
            }
        }

        return 0;
    }
//    public static String getCountryCodeLabel(int code) {
//        for(int i = 0, length = COUNTRY_CODE.length; i < length; i++) {
//            if(COUNTRY_CODE[i] == code) {
//                return COUNTRY_NAME[i] + " (+" + code + ")";
//            }
//        }
//
//        return COUNTRY_NAME[0] + " (+" + COUNTRY_CODE[0] + ")";
//    }
}
